version: '3'
services:
  web:
    image: nginx:latest
    ports:
      - "8080:8080"
    volumes:
      - ./api:/var/www
      - ./docker/nginx/site.conf:/etc/nginx/conf.d/site.conf
    links:
      - php
  php:
    container_name: api_php
    build: ./docker/php
    env_file:
      - .env
    volumes:
      - ./api:/var/www/
    working_dir: /var/www/
    links:
      - mysql
    depends_on:
      - mysql

  mysql:
    image: mysql:5.7
    container_name: app_mysql
    restart: always
    volumes:
      - ./docker/db:/var/lib/mysql
    ports:
      - 3307:3306
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: app_phpmyadmin
    restart: always
    ports:
      - 8181:80
    links:
      - mysql
    environment:
      PMA_HOST: mysql
